
/**
 * Autogenerated file by the build process, please do not modify by hand!
 */
export const SLACK_WEBHOOK_URL = 'undefined';
export const BUILD_ID = 'undefined';
export const CONTEXT = 'undefined';
export const REPOSITORY_URL = 'undefined';
export const COMMIT_REF = 'undefined';
export const BUILD_TIMESTAMP = '2020-01-27T17:34:22.988Z';
