/**
 * Will be autogenerated
 */
export const SLACK_WEBHOOK_URL = 'undefined';
export const BUILD_ID = 'undefined';
export const CONTEXT = 'undefined';
export const REPOSITORY_URL = 'undefined';
export const COMMIT_REF = 'undefined';
export const BUILD_TIMESTAMP = '2020-01-25T23:37:53.571Z';
