
/**
 * Autogenerated file by the build process, please do not modify by hand!
 */
export const SLACK_WEBHOOK_URL = 'undefined';
export const BUILD_ID = 'undefined';
export const CONTEXT = 'undefined';
export const REPOSITORY_URL = 'undefined';
export const COMMIT_REF = 'undefined';
export const COCKPIT_URL = 'https://cockpit.rheinklang-festival.ch';
export const FESTIVAL_SITE = 'https://rheinklang-festival.ch';
export const BUILD_TIMESTAMP = '2020-01-27T17:42:13.254Z';
